// Package agent implements the agentic loop and the event types it emits.
package agent

import (
	"time"

	"github.com/cloudshuttle/drover-code/internal/api"
)

// Event is the discriminated union of all messages the agent loop sends
// to its consumer (BubbleTea TUI in Phase 2, plain stdout in Phase 1).
//
// The consumer reads from a chan Event and updates its view accordingly.
// Events arrive in the order things happen; the consumer must never block
// the channel receive because the loop will also block.
type Event interface {
	isAgentEvent()
}

// TextDeltaEvent carries a streaming text fragment from the model.
// These arrive rapidly and should be appended to the current output buffer.
type TextDeltaEvent struct {
	Text string
}

func (TextDeltaEvent) isAgentEvent() {}

// ToolStartEvent signals that the loop is about to execute a tool.
// Emitted after permission is granted, before Execute is called.
type ToolStartEvent struct {
	// CallIndex is the position of this tool call within the current response.
	// Useful for rendering multiple concurrent tool spinners.
	CallIndex int
	// ID is the tool_use_id from the model's response.
	ID string
	// Name is the tool name, e.g. "bash" or "read_file".
	Name string
	// InputSummary is a short human-readable summary of the input,
	// generated by the loop. Safe to show to the user.
	InputSummary string
}

func (ToolStartEvent) isAgentEvent() {}

// ToolDoneEvent signals that a tool execution has completed.
type ToolDoneEvent struct {
	CallIndex int
	ID        string
	Name      string
	// IsError is true when the tool returned an error.
	IsError bool
	// OutputSummary is a short (≤80 char) preview of the output.
	OutputSummary string
}

func (ToolDoneEvent) isAgentEvent() {}

// PermissionRequestEvent is emitted when a tool needs user authorisation.
// The TUI should render a permission prompt and send the decision back
// via the DecisionCh channel.
//
// The loop blocks until a decision is received (or ctx is cancelled).
type PermissionRequestEvent struct {
	ToolName string
	Input    []byte
	Summary  string
	// DecisionCh is a send-once channel the TUI writes the user's decision to.
	DecisionCh chan<- PermissionDecision
}

type PermissionBatchItem struct {
	ToolName string
	Input    []byte
	Summary  string
}

// PermissionBatchRequestEvent is emitted when plan-mode wants a single batch
// approval for multiple permission-requiring tool calls.
//
// The TUI should present the list and send one decision back via DecisionCh.
// The decision applies to all items in the batch.
type PermissionBatchRequestEvent struct {
	Items []PermissionBatchItem
	// DecisionCh is a send-once channel the TUI writes the user's decision to.
	DecisionCh chan<- PermissionDecision
}

// PermissionDecision is sent by the TUI back to the loop.
type PermissionDecision int

const (
	PermAllow PermissionDecision = iota
	PermAlwaysAllow
	PermDeny
	PermAppliedManually
)

func (PermissionRequestEvent) isAgentEvent() {}
func (PermissionBatchRequestEvent) isAgentEvent() {}

// UsageEvent carries token consumption for the last API call.
// Emitted after each streaming response completes.
type UsageEvent struct {
	api.Usage
	// TotalInputTokens and TotalOutputTokens are cumulative for the session.
	TotalInputTokens  int
	TotalOutputTokens int
}

func (UsageEvent) isAgentEvent() {}

// HeartbeatEvent is emitted periodically while Run is active so orchestrators
// can tell a long-running agent from a hung process. Interval is controlled by
// DROVER_CODE_HEARTBEAT_INTERVAL_SECS (default 30; 0 disables).
type HeartbeatEvent struct {
	// Turn is the current agentic turn (1-based), best-effort.
	Turn int
	// Time is UTC.
	Time time.Time
}

func (HeartbeatEvent) isAgentEvent() {}

// CompactionStartEvent signals context summarisation before the main model stream.
// Emitted once per compaction round (automatic budget compaction or /compact).
type CompactionStartEvent struct {
	Round                 int // 1-based index within the current compaction burst
	MaxRounds             int // upper bound on automatic rounds (e.g. 3)
	EstimatedTokensBefore int // convo heuristic before this round
}

func (CompactionStartEvent) isAgentEvent() {}

// CompactionDoneEvent signals a compaction round finished (check Err).
type CompactionDoneEvent struct {
	Round                 int
	EstimatedTokensAfter  int
	Duration              time.Duration
	Err                   error // nil on success
}

func (CompactionDoneEvent) isAgentEvent() {}

// DoneEvent signals that the agent loop has finished processing the user's
// request and is ready for the next input.
type DoneEvent struct{}

func (DoneEvent) isAgentEvent() {}

// ErrorEvent carries a fatal error from the loop.
// After this event the loop has returned; the consumer should show the error.
type ErrorEvent struct {
	Err error
}

func (ErrorEvent) isAgentEvent() {}

