// Package planning provides tools for agent memory and task planning.
package planning

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/cloudshuttle/drover-code/internal/tools/toolutil"
)

// WritePlan implements the write_plan tool.
type WritePlan struct {
	WorkDir string
}

type planInput struct {
	Content string `json:"content"`
	Title   string `json:"title,omitempty"`
}

func (t *WritePlan) Name() string { return "write_plan" }

func (t *WritePlan) Description() string {
	return "Create or update PLAN.md in the root directory for complex, multi-step tasks. " +
		"Use this tool to track your progress and maintain state over long-running operations."
}

func (t *WritePlan) InputSchema() json.RawMessage {
	return toolutil.NewSchema("object").
		Prop("content", toolutil.NewSchema("string").Desc("Full plan content (Markdown formatting).")).
		Prop("title", toolutil.NewSchema("string").Desc("Optional title for the plan.")).
		Required("content").
		Build()
}

func (t *WritePlan) NeedsPermission(rawInput json.RawMessage) bool { return false } // Writing a plan is safe

func (t *WritePlan) Execute(ctx context.Context, rawInput json.RawMessage) (string, error) {
	var inp planInput
	if err := json.Unmarshal(rawInput, &inp); err != nil {
		return "", fmt.Errorf("write_plan: bad input: %w", err)
	}

	if inp.Content == "" {
		return "", fmt.Errorf("content is required")
	}

	title := inp.Title
	if title == "" {
		title = "Current Task Plan"
	}

	planPath := filepath.Join(t.WorkDir, "PLAN.md")

	header := fmt.Sprintf("# %s\n\n**Generated by drover-code • %s**\n\n", title, time.Now().Format("2006-01-02 15:04"))
	fullContent := header + inp.Content

	if err := os.WriteFile(planPath, []byte(fullContent), 0644); err != nil {
		return "", fmt.Errorf("failed to write PLAN.md: %w", err)
	}

	return fmt.Sprintf("✅ PLAN.md written successfully (%d characters). You should continually update this file as you progress.", len(fullContent)), nil
}
