package warden

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sync"
	"time"

	otellog "go.opentelemetry.io/otel/log"
	otellogglobal "go.opentelemetry.io/otel/log/global"

	"github.com/cloudshuttle/drover-code/internal/telemetry"
	"github.com/cloud-shuttle/drover-warden/warden"
)

var (
	globalWarden *warden.WardenMiddleware
	once         sync.Once
	initErr      error
)

// ResetForTest clears the singleton so tests can exercise both disabled and active
// (with different beads dirs) paths in the same test binary run.
// Exported for use by other packages' tests (e.g. permissions engine tests).
// For testing use only.
func ResetForTest() {
	globalWarden = nil
	initErr = nil
	once = sync.Once{}
}

// resetForTest is the internal alias used by this package's own tests.
func resetForTest() { ResetForTest() }
// Init initializes the global Warden instance from the DROVER_WARDEN_BEADS_DIR
// environment variable (primary), falling back to shipped default beads for the
// unikernel preset / dev / packaged runs when the env is unset.
// Safe to call multiple times; only the first call matters.
// If no beads dir found, Warden is disabled (no-op, zero cost).
func Init() error {
	once.Do(func() {
		beadsDir := os.Getenv("DROVER_WARDEN_BEADS_DIR")
		if beadsDir == "" {
			beadsDir = resolveDefaultBeadsDir()
		}
		if beadsDir == "" {
			return // disabled
		}
		globalWarden, initErr = warden.NewWarden(beadsDir)
	})
	return initErr
}

// resolveDefaultBeadsDir looks for a policies.jsonl in well-known locations
// (cwd-relative for dev, packaged share dir, next to binary). Returns "" if none.
func resolveDefaultBeadsDir() string {
	candidates := []string{
		"beads",
		filepath.Join("drover-code", "beads"),
		"/usr/local/share/drover-code/beads",
	}
	if exe, err := os.Executable(); err == nil {
		d := filepath.Dir(exe)
		candidates = append(candidates,
			filepath.Join(d, "beads"),
			filepath.Join(d, "..", "share", "drover-code", "beads"),
			filepath.Join(d, "..", "beads"),
		)
	}
	for _, c := range candidates {
		if c == "" {
			continue
		}
		p := filepath.Clean(c)
		if _, err := os.Stat(filepath.Join(p, "policies.jsonl")); err == nil {
			return p
		}
	}
	return ""
}

// Get returns the initialized Warden middleware, or nil if not configured.
func Get() *warden.WardenMiddleware {
	_ = Init() // ensure initialized
	return globalWarden
}

// CheckAction is a convenience wrapper. If Warden is not configured, it returns
// an allow decision.
func CheckAction(ctx context.Context, req *warden.GuardRequest) warden.Decision {
	w := Get()
	if w == nil {
		return warden.Decision{
			Allowed: true,
			Result: warden.GuardResult{
				Result: "passed",
				Reason: "warden disabled",
			},
		}
	}
	dec := w.CheckAction(ctx, req)
	emitWardenDecision(ctx, "action", req, dec)
	return dec
}

// CheckInput is the convenience wrapper for input/prompt guards (e.g. prompt injection).
// If Warden disabled, returns allow.
func CheckInput(ctx context.Context, req *warden.GuardRequest) warden.Decision {
	w := Get()
	if w == nil {
		return warden.Decision{
			Allowed: true,
			Result: warden.GuardResult{
				Result: "passed",
				Reason: "warden disabled",
			},
		}
	}
	dec := w.CheckInput(ctx, req)
	emitWardenDecision(ctx, "input", req, dec)
	return dec
}

// CheckOutput guards model responses (text generated by LLM). Handles the streaming
// collection case in the agent loop (full turn content after streamResponse).
// If disabled, allow.
func CheckOutput(ctx context.Context, req *warden.GuardRequest) warden.Decision {
	w := Get()
	if w == nil {
		return warden.Decision{
			Allowed: true,
			Result: warden.GuardResult{
				Result: "passed",
				Reason: "warden disabled",
			},
		}
	}
	dec := w.CheckOutput(ctx, req)
	emitWardenDecision(ctx, "output", req, dec)
	return dec
}

// CheckToolCall builds a GuardRequest for a tool invocation (used by permissions.Engine
// to let Warden participate in the unified permitFn decision). Best-effort arg parse.
func CheckToolCall(ctx context.Context, toolName string, input []byte) warden.Decision {
	var args map[string]any
	if len(input) > 0 {
		_ = json.Unmarshal(input, &args)
	}
	return CheckAction(ctx, &warden.GuardRequest{
		TenantID: os.Getenv("DROVER_TENANT_ID"),
		ToolCall: &warden.ToolCall{
			ToolName: toolName,
			Args:     args,
		},
		Context: map[string]any{
			"agent_id": os.Getenv("DROVER_AGENT_ID"),
		},
	})
}

// emitWardenDecision wires the Warden semantic decision to all configured backends:
// - Langfuse scores (for agent traces)
// - ClickHouse (warden_decisions table) for cross-layer correlation with Guard in ClickStack/HyperDX
func emitWardenDecision(ctx context.Context, checkType string, req *warden.GuardRequest, dec warden.Decision) {
	// 1. Existing Langfuse score emission
	if tid := telemetry.TraceIDFrom(ctx); tid != "" {
		v := 1.0
		if !dec.Allowed {
			v = 0.0
		}
		telemetry.TracerFrom(ctx).Score(tid, "warden."+checkType, v, telemetry.ScoreSourceAPI, dec.Result.Reason)
	}

	// 2. ClickHouse emission (best effort, for governance correlation)
	logToClickHouse(ctx, checkType, req, dec)

	// 3. OTEL log emission (long-term preferred path)
	// This allows Warden decisions to flow through the OTEL collector into ClickHouse
	// like all other platform signals (traces, logs, metrics).
	emitWardenDecisionAsOTELLog(ctx, checkType, req, dec)
}

// emitWardenScore is the legacy name kept for backward compatibility inside this package.
// It now delegates to the richer emitWardenDecision.
func emitWardenScore(ctx context.Context, name string, dec warden.Decision) {
	// Best effort extraction of check type from the score name (e.g. "warden.action")
	checkType := "unknown"
	if len(name) > 7 && name[:7] == "warden." {
		checkType = name[7:]
	}

	// We don't have the original req here in the legacy path — create a minimal one from context/env
	req := &warden.GuardRequest{
		TenantID: getEnvOrContext(ctx, "DROVER_TENANT_ID"),
		Context: map[string]any{
			"agent_id": getEnvOrContext(ctx, "DROVER_AGENT_ID"),
			"job_id":   getEnvOrContext(ctx, "DROVER_JOB_ID"),
		},
	}

	emitWardenDecision(ctx, checkType, req, dec)
}

func getEnvOrContext(ctx context.Context, key string) string {
	if v := ctx.Value(contextKey(key)); v != nil {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

// contextKey is a tiny helper to avoid polluting the context package
type contextKey string

// emitWardenDecisionAsOTELLog emits the Warden decision as a structured OTEL log record.
// This is the long-term preferred path: decisions flow through the OTEL collector
// (same as Gateway traces) into ClickHouse, where they can be correlated with Guard.
func emitWardenDecisionAsOTELLog(ctx context.Context, checkType string, req *warden.GuardRequest, dec warden.Decision) {
	logger := otellogglobal.Logger("drover.warden")

	rec := otellog.Record{}
	rec.SetTimestamp(time.Now())
	rec.SetBody(otellog.StringValue("Warden semantic decision"))

	rec.AddAttributes(
		otellog.String("drover.warden.check_type", checkType),
		otellog.Bool("drover.warden.allowed", dec.Allowed),
		otellog.String("drover.warden.reason", dec.Result.Reason),
		otellog.String("drover.warden.result", dec.Result.Result),
		otellog.Int64("drover.warden.latency_ms", dec.Result.LatencyMS),
		otellog.String("drover.warden.bead_id", dec.Result.BeadID),
	)

	if req.TenantID != "" {
		rec.AddAttributes(otellog.String("drover.tenant_id", req.TenantID))
	}
	if jobID := getEnvOrContext(ctx, "DROVER_JOB_ID"); jobID != "" {
		rec.AddAttributes(otellog.String("drover.job_id", jobID))
	}
	if agentID := getEnvOrContext(ctx, "DROVER_AGENT_ID"); agentID != "" {
		rec.AddAttributes(otellog.String("drover.agent_id", agentID))
	}
	if req.ToolCall != nil && req.ToolCall.ToolName != "" {
		rec.AddAttributes(otellog.String("drover.warden.tool_name", req.ToolCall.ToolName))
	}

	logger.Emit(ctx, rec)
}
